# Generated by Django 6.0.1 on 2026-01-21 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='doctors_images/')),
                ('speciality', models.CharField(choices=[('eyes', 'Ophthalmologist'), ('heart', 'Cardiologist'), ('generaliste', 'General Practitioner'), ('dentist', 'Dentist'), ('pediatrics', 'Pediatrician'), ('neurology', 'Neurologist')], max_length=100)),
                ('number_of_phone', models.CharField(max_length=20)),
                ('instagram_account', models.CharField(max_length=100)),
                ('inpe', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_type', models.CharField(choices=[('cabinet', 'Cabinet'), ('clinic', 'Clinic'), ('hospital', 'Hospital'), ('laboratory', 'Laboratory')], default='cabinet', max_length=50)),
                ('establishment_name', models.CharField(max_length=200)),
                ('localization', models.URLField(blank=True, null=True)),
                ('ville', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse_electronique', models.EmailField(max_length=254)),
                ('telephone_fixe', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='establishment_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_establishment', to='account.doctor')),
            ],
        ),
    ]
