# Generated by Django 6.0.1 on 2026-02-25 20:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='doctor_images'),
        ),
    ]
