# Generated by Django 6.0.1 on 2026-02-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_establishment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
