# Generated by Django 6.0.1 on 2026-01-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_set_doctor_acceptance_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Whether the doctor has been accepted by admin'),
        ),
    ]
