# Generated by Django 6.0.1 on 2026-01-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_doctor_img_alter_doctor_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_establishment', to='account.doctor'),
        ),
    ]
