# Generated by Django 6.0.1 on 2026-01-09 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_username', models.CharField(max_length=100)),
                ('instagram_user_id', models.CharField(blank=True, max_length=100)),
                ('question_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_sent', models.BooleanField(default=False)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
