# Generated by Django 6.0.1 on 2026-01-31 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_username', models.CharField(max_length=100)),
                ('instagram_user_id', models.CharField(blank=True, max_length=100)),
                ('question_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('views_count', models.IntegerField(default=0, help_text='Number of views for this question')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_sent', models.BooleanField(default=False, help_text='Whether the answer has been sent to the user')),
                ('views_count', models.IntegerField(default=0, help_text='Number of views for this answer')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.OneToOneField(help_text='One answer per question', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
