# Generated by Django 6.0.1 on 2026-01-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
