# Generated by Django 6.0.1 on 2026-01-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_separate_answer_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Number of views for this question'),
        ),
    ]
